### ISSUE TITLE
FileSystemException: Creation failed, path = '.local-chromium' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by talhakhan1297** [DAMMAK/FastNet#1]
/flutter (16193): #0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
E/flutter (16193): #1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter (16193): #2      downloadChrome
package:puppeteer/src/downloader.dart:27
E/flutter (16193): #3      _inferExecutablePath
package:puppeteer/src/puppeteer.dart:330
E/flutter (16193): #4      Puppeteer.launch
package:puppeteer/src/puppeteer.dart:140

**Comment by DAMMAK** [comment]
at the moment it doesn't work for mobile due to the Mobile Manufacturer policy of using the headless browser in mobile... but I'm already looking into another solution by using socket implementation

**Comment by talhakhan1297** [comment]
Then why does the pub page says that it supports both Android and iOS
![image](https://user-images.githubusercontent.com/50271102/100104469-089f0000-2e88-11eb-928a-0cacee493a3b.png)

Please mention it in the Readme section.

**Comment by DAMMAK** [comment]
> Then why does the pub page says that it supports both Android and iOS
> ![image](https://user-images.githubusercontent.com/50271102/100104469-089f0000-2e88-11eb-928a-0cacee493a3b.png)
> 
> Please mention it in the Readme section.

Yeah, I will update the ReadMe... the part where it started IOS and Android was automatically done by Dart itself... I don't have control over that...

**Comment by talhakhan1297** [comment]
> > Then why does the pub page says that it supports both Android and iOS
> > ![image](https://user-images.githubusercontent.com/50271102/100104469-089f0000-2e88-11eb-928a-0cacee493a3b.png)
> > Please mention it in the Readme section.
> 
> Yeah, I will update the ReadMe... the part where it started IOS and Android was automatically done by Dart itself... I don't have control over that...

I have seen some packages that only support a certain platform and only that platform is mentioned. (e.g. [android_alarm_manager](https://pub.dev/packages/android_alarm_manager))

**Comment by DAMMAK** [comment]
> > > Then why does the pub page says that it supports both Android and iOS
> > > ![image](https://user-images.githubusercontent.com/50271102/100104469-089f0000-2e88-11eb-928a-0cacee493a3b.png)
> > > Please mention it in the Readme section.
> > 
> > 
> > Yeah, I will update the ReadMe... the part where it started IOS and Android was automatically done by Dart itself... I don't have control over that...
> 
> I have seen some packages that only support a certain platform and only that platform is mentioned. (e.g. [android_alarm_manager](https://pub.dev/packages/android_alarm_manager))

Yeah like I said it was automatically.. it is Dart analyzer that does all that... it analyzed the code and determines the compatibility.... 

What I did suppose to support all platform it was just that it throws the error because of the mobile manufacturer policy...

Dart analyzer only analyzes code...
